name: Lint Ansible Playbooks
on:
  pull_request:
    paths:
      - 'ansible/**'
  push:
    paths:
      - 'ansible/**'
jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
